# Generated by Django 4.2.7 on 2023-11-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='blog.books'),
        ),
    ]
